title : "rohanieyvette"
email : "rohanie.ariola@gmail.com"
description : "little-laughing-machine"
baseurl : "/london-site"
url : "http://rohanieyvette.com"

# Build settings
markdown : rdiscount
rdiscount :
   extensions : [smart]
permalink : /articles/:title
#theme: minima
#plugins:
#  - jekyll-feed
